version: '3.8'

services:
  avito_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@postgres:5432/avito_db?sslmode=disable
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito_db

      - SERVER_PORT=8080
      - JWT_SECRET_KEY=secret
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - internal

  postgres:
    image: postgres:latest
    volumes:
      - ./migrations:/migrations
      - ./database/avito_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito_db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d avito_db" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

networks:
  internal: